azure:
  store_build_artifacts: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
conda_build:
  pkg_format: '2'
