# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.22python3.10.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.22python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_h495a96f2b1
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.22python3.9.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.22python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_hda0a85dc29
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.23python3.11.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_hc366c38746
      win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.26python3.12.____cpython:
        CONFIG: win_64_cuda_compilercuda-nvcccuda_compiler_version12.0numpy1.26python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilercuda-nvcccuda_c_h4d326a778f
      win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.22python3.10.____cpython:
        CONFIG: win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.22python3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilernvcccuda_compil_h82f22d9b2c
      win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.22python3.9.____cpython:
        CONFIG: win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.22python3.9.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilernvcccuda_compil_hfc9e120a9c
      win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.23python3.11.____cpython:
        CONFIG: win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.23python3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilernvcccuda_compil_h8be27f826d
      win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.26python3.12.____cpython:
        CONFIG: win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.26python3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: win_64_cuda_compilernvcccuda_compil_h7c89bdb50c
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    UPLOAD_TEMP: D:\\tmp

  steps:

    - task: PythonScript@0
      displayName: 'Download Miniforge'
      inputs:
        scriptSource: inline
        script: |
          import urllib.request
          url = 'https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe'
          path = r"$(Build.ArtifactStagingDirectory)/Miniforge.exe"
          urllib.request.urlretrieve(url, path)

    - script: |
        start /wait "" %BUILD_ARTIFACTSTAGINGDIRECTORY%\Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=C:\Miniforge
      displayName: Install Miniforge

    - powershell: Write-Host "##vso[task.prependpath]C:\Miniforge\Scripts"
      displayName: Add conda to PATH

    - script: |
        call ".scripts\run_win_build.bat"
      displayName: Run Windows build
      env:
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
    - script: |
        set CI=azure
        set CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        set FEEDSTOCK_NAME=$(build.Repository.Name)
        set ARTIFACT_STAGING_DIR=$(Build.ArtifactStagingDirectory)
        set CONDA_BLD_DIR=$(CONDA_BLD_PATH)
        set BLD_ARTIFACT_PREFIX=conda_artifacts
        if "%AGENT_JOBSTATUS%" == "Failed" (
            set ENV_ARTIFACT_PREFIX=conda_envs
        )
        call ".scripts\create_conda_build_artifacts.bat"
      displayName: Prepare conda build artifacts
      condition: succeededOrFailed()

    - task: PublishPipelineArtifact@1
      displayName: Store conda build artifacts
      condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(BLD_ARTIFACT_PATH)
        artifactName: $(BLD_ARTIFACT_NAME)

    - task: PublishPipelineArtifact@1
      displayName: Store conda build environment artifacts
      condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
      inputs:
        targetPath: $(ENV_ARTIFACT_PATH)
        artifactName: $(ENV_ARTIFACT_NAME)